# Generated by Django 6.1.1 on 2026-09-10 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0002_order_orderitem_order_order_total_price_gte_001_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='reservation_quantity_gte_1')],
            },
        ),
    ]
